# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_and_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('HR_ADMIN', 'HR Admin'), ('HR_MAKER', 'HR Maker'), ('HR_CHECKER', 'HR Checker'), ('HIRING_MANAGER', 'Hiring Manager'), ('INTERVIEWER', 'Interviewer'), ('RECRUITER', 'Recruiter'), ('FINANCE_CHECKER', 'Finance Checker'), ('TALENT_COMMITTEE', 'Talent Committee'), ('HR_PERFORMANCE', 'HR Performance Officer'), ('LD_OFFICER', 'L&D Officer'), ('LD_CHECKER', 'L&D Checker'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('APPLICANT', 'Applicant'), ('PAYROLL_OFFICER', 'Payroll Officer'), ('HSE_OFFICER', 'HSE Officer'), ('SERVICE_DESK_AGENT', 'Service Desk Agent'), ('ER_OFFICER', 'Employee Relations Officer'), ('BENEFITS_ADMIN', 'Benefits Administrator')], default='EMPLOYEE', max_length=30),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
