# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0006_location_employee_employment_type_employmentcontract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0002_workflowattachment_workflowactor'),
        ('workforce', '0003_holidaycalendar_shifttemplate_leavepolicy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffboardingCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('IN_PROGRESS', 'In Progress'), ('CLEARANCE_PENDING', 'Clearance Pending'), ('PENDING_SETTLEMENT', 'Pending Settlement'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=25)),
                ('notice_period_days', models.PositiveIntegerField(default=0)),
                ('last_working_date', models.DateField(blank=True, null=True)),
                ('exit_interview_scheduled_date', models.DateField(blank=True, null=True)),
                ('knowledge_handover_due', models.DateField(blank=True, null=True)),
                ('rehire_eligible', models.BooleanField(default=True)),
                ('rehire_notes', models.TextField(blank=True)),
                ('legal_hold', models.BooleanField(default=False)),
                ('final_settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('settlement_status', models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('settlement_paid_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offboarding_case', to='core_hr.employee')),
                ('hr_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_cases_owned', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offboarding_cases_initiated', to=settings.AUTH_USER_MODEL)),
                ('separation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_case', to='workforce.separation')),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'offboard_case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basic_pay_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leave_encashment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gratuity_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notice_pay_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('asset_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_additions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_settlement', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash')], default='BANK_TRANSFER', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_approved', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_settlements', to='offboarding.offboardingcase')),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'offboard_final_settlement',
            },
        ),
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_date', models.DateField()),
                ('format', models.CharField(choices=[('IN_PERSON', 'In Person'), ('VIDEO', 'Video Call'), ('WRITTEN', 'Written'), ('PHONE', 'Phone')], max_length=20)),
                ('reason_for_leaving', models.TextField(blank=True)),
                ('overall_experience', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('NEUTRAL', 'Neutral'), ('POOR', 'Poor'), ('VERY_POOR', 'Very Poor')], max_length=20, null=True)),
                ('would_return', models.BooleanField(blank=True, null=True)),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('overall_sentiment', models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative')], max_length=20, null=True)),
                ('is_confidential', models.BooleanField(default=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interviews', to='offboarding.offboardingcase')),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_interviews_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offboard_exit_interview',
            },
        ),
        migrations.CreateModel(
            name='ClearanceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('task_type', models.CharField(choices=[('IT_ACCESS', 'IT Access'), ('ASSET_RETURN', 'Asset Return'), ('FINANCE_CLEARANCE', 'Finance Clearance'), ('LIBRARY', 'Library'), ('ADMIN', 'Admin'), ('MEDICAL', 'Medical'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('WAIVED', 'Waived'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20)),
                ('completion_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_tasks', to='offboarding.offboardingcase')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_tasks_completed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offboard_clearance_task',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetClearance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_code', models.CharField(blank=True, max_length=100)),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'Laptop'), ('PHONE', 'Phone'), ('TABLET', 'Tablet'), ('BADGE', 'Badge/Card'), ('VEHICLE', 'Vehicle'), ('KEYS', 'Keys'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], max_length=20)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('return_status', models.CharField(choices=[('PENDING', 'Pending'), ('RETURNED', 'Returned'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('NOT_APPLICABLE', 'Not Applicable')], default='PENDING', max_length=20)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('condition_on_return', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('UNUSABLE', 'Unusable')], max_length=20, null=True)),
                ('condition_notes', models.TextField(blank=True)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_clearances', to='offboarding.offboardingcase')),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_clearances_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offboard_asset_clearance',
            },
        ),
        migrations.CreateModel(
            name='AccessRevocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_name', models.CharField(max_length=255)),
                ('access_type', models.CharField(choices=[('NETWORK', 'Network'), ('EMAIL', 'Email'), ('VPN', 'VPN'), ('ERP', 'ERP System'), ('PHYSICAL', 'Physical Access'), ('CLOUD', 'Cloud Services'), ('DATABASE', 'Database'), ('OTHER', 'Other')], max_length=20)),
                ('access_identifier', models.CharField(blank=True, max_length=255)),
                ('scheduled_revocation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVOKED', 'Revoked'), ('FAILED', 'Failed'), ('NOT_APPLICABLE', 'Not Applicable')], default='PENDING', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_revocations', to='offboarding.offboardingcase')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_revocations_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offboard_access_revocation',
            },
        ),
    ]
