# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0006_location_employee_employment_type_employmentcontract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0002_workflowattachment_workflowactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERCaseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_grievance', models.BooleanField(default=False)),
                ('is_disciplinary', models.BooleanField(default=False)),
                ('is_confidential', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'er_case_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ERCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('case_type', models.CharField(choices=[('GRIEVANCE', 'Grievance'), ('DISCIPLINARY', 'Disciplinary'), ('MISCONDUCT', 'Misconduct'), ('POOR_PERFORMANCE', 'Poor Performance'), ('ATTENDANCE', 'Attendance'), ('FRAUD', 'Fraud'), ('OTHER', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('HEARING_SCHEDULED', 'Hearing Scheduled'), ('HEARING_COMPLETED', 'Hearing Completed'), ('OUTCOME_ISSUED', 'Outcome Issued'), ('APPEALED', 'Appealed'), ('CLOSED', 'Closed'), ('WITHDRAWN', 'Withdrawn')], default='OPEN', max_length=30)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('MAJOR', 'Major'), ('GROSS_MISCONDUCT', 'Gross Misconduct')], default='MINOR', max_length=20)),
                ('legal_hold', models.BooleanField(default=False)),
                ('confidential', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='er_cases_investigating', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='employee_relations.ercasecategory')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='er_cases_opened', to=settings.AUTH_USER_MODEL)),
                ('subject_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='er_cases_as_subject', to='core_hr.employee')),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'er_case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ERAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appeal_date', models.DateField()),
                ('appeal_reason', models.TextField()),
                ('grounds_of_appeal', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('UPHELD', 'Upheld'), ('PARTIALLY_UPHELD', 'Partially Upheld'), ('DISMISSED', 'Dismissed'), ('WITHDRAWN', 'Withdrawn')], default='SUBMITTED', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appellant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='er_appeals', to='core_hr.employee')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appeals', to='employee_relations.ercase')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='er_appeals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'er_appeal',
                'ordering': ['-appeal_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('COMPLAINANT', 'Complainant'), ('RESPONDENT', 'Respondent'), ('WITNESS', 'Witness'), ('INVESTIGATOR', 'Investigator'), ('PANEL_MEMBER', 'Panel Member'), ('ADVOCATE', 'Advocate')], max_length=20)),
                ('coi_declared', models.BooleanField(default=False)),
                ('coi_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='employee_relations.ercase')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='er_case_roles', to='core_hr.employee')),
            ],
            options={
                'db_table': 'er_case_party',
            },
        ),
        migrations.CreateModel(
            name='CaseOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome_type', models.CharField(choices=[('VERBAL_WARNING', 'Verbal Warning'), ('WRITTEN_WARNING', 'Written Warning'), ('FINAL_WARNING', 'Final Warning'), ('SUSPENSION', 'Suspension'), ('DEMOTION', 'Demotion'), ('TERMINATION', 'Termination'), ('DISMISSED', 'Dismissed'), ('REINSTATEMENT', 'Reinstatement'), ('NO_ACTION', 'No Action')], max_length=30)),
                ('effective_date', models.DateField()),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('outcome_details', models.TextField(blank=True)),
                ('letter_issued', models.BooleanField(default=False)),
                ('letter_issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='employee_relations.ercase')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='er_outcomes_decided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'er_case_outcome',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseHearing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hearing_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('hearing_type', models.CharField(choices=[('PRELIMINARY', 'Preliminary'), ('INVESTIGATIVE', 'Investigative'), ('DISCIPLINARY', 'Disciplinary'), ('APPEAL', 'Appeal')], default='DISCIPLINARY', max_length=20)),
                ('panel_members', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('outcome_summary', models.TextField(blank=True)),
                ('minutes', models.FileField(blank=True, null=True, upload_to='er/hearings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='employee_relations.ercase')),
            ],
            options={
                'db_table': 'er_case_hearing',
                'ordering': ['hearing_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('WITNESS_STATEMENT', 'Witness Statement'), ('CCTV', 'CCTV Footage'), ('EMAIL', 'Email'), ('SYSTEM_LOG', 'System Log'), ('PHOTOGRAPH', 'Photograph'), ('OTHER', 'Other')], max_length=30)),
                ('document', models.FileField(blank=True, null=True, upload_to='er/evidence/')),
                ('is_confidential', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='er_evidence_added', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='employee_relations.ercase')),
            ],
            options={
                'db_table': 'er_case_evidence',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ercase',
            index=models.Index(fields=['status'], name='er_case_status_a48690_idx'),
        ),
        migrations.AddIndex(
            model_name='ercase',
            index=models.Index(fields=['subject_employee'], name='er_case_subject_25183e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caseparty',
            unique_together={('case', 'employee', 'role')},
        ),
    ]
