# Generated by Django 4.2.16 on 2026-05-25 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('profile_status', models.CharField(choices=[('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=20)),
                ('consent_version', models.CharField(default='1.0', max_length=50)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rec_applicant',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_COMPLETED', 'Interview Completed'), ('OFFERED', 'Offered'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('ONBOARDING', 'Onboarding'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='APPLIED', max_length=30)),
                ('cover_letter', models.TextField(blank=True)),
                ('screening_answers', models.JSONField(blank=True, default=dict)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='recruitment.applicant')),
            ],
            options={
                'db_table': 'rec_application',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_type', models.CharField(choices=[('PHONE', 'Phone Screen'), ('VIDEO', 'Video'), ('ONSITE', 'On-Site'), ('PANEL', 'Panel'), ('TECHNICAL', 'Technical')], default='VIDEO', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('location_or_link', models.CharField(blank=True, max_length=500)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.application')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviews_created', to=settings.AUTH_USER_MODEL)),
                ('panel', models.ManyToManyField(blank=True, related_name='panel_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rec_interview',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.JSONField(blank=True, default=dict)),
                ('total_package', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('employment_type', models.CharField(default='FULL_TIME', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='DRAFT', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('negotiation_notes', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='recruitment.application')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers_created', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_hr.grade')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_hr.position')),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'rec_offer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisition_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('hiring_reason', models.CharField(choices=[('REPLACEMENT', 'Replacement'), ('EXPANSION', 'Expansion'), ('SUCCESSION_GAP', 'Succession Gap'), ('NEW_ROLE', 'New Role')], max_length=30)),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CHECKED', 'Checked'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('budget_confirmed', models.BooleanField(default=False)),
                ('headcount', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='core_hr.position')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions_made', to=settings.AUTH_USER_MODEL)),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'rec_job_requisition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('INTERNAL', 'Internal Only'), ('EXTERNAL', 'External Only'), ('BOTH', 'Internal & External'), ('CONFIDENTIAL', 'Confidential')], default='BOTH', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('SCREENING', 'Screening'), ('INTERVIEW', 'Interview'), ('OFFER_DRAFT', 'Offer Draft'), ('OFFER_SUBMITTED', 'Offer Submitted'), ('OFFER_APPROVED', 'Offer Approved'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('ONBOARDING_STARTED', 'Onboarding Started'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('screening_questions', models.JSONField(blank=True, default=list)),
                ('eligibility_criteria', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings_created', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='recruitment.jobrequisition')),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'rec_job_posting',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('section_scores', models.JSONField(blank=True, default=dict)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('recommendation', models.CharField(choices=[('PROCEED', 'Proceed'), ('HOLD', 'Hold'), ('REJECT', 'Reject')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='recruitment.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interview_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rec_interview_feedback',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='recruitment.jobposting'),
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True)),
                ('education', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='recruitment.applicant')),
            ],
            options={
                'db_table': 'rec_applicant_profile',
            },
        ),
        migrations.AddIndex(
            model_name='jobrequisition',
            index=models.Index(fields=['position', 'status'], name='rec_job_req_positio_2466fd_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['status', 'visibility'], name='rec_job_pos_status_74f208_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewfeedback',
            unique_together={('interview', 'interviewer')},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job_posting', 'stage'], name='rec_applica_job_pos_71b8ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('applicant', 'job_posting'), name='uq_applicant_per_posting'),
        ),
    ]
