# Generated by Django 4.2.16 on 2026-06-02 06:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_application_workflow_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('RESUME', 'Resume / CV'), ('COVER_LETTER', 'Cover Letter'), ('ACADEMIC_CERT', 'Academic Certificate'), ('IDENTITY', 'Identity Document'), ('PORTFOLIO', 'Portfolio'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='applicant_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recruitment.applicant')),
            ],
            options={
                'db_table': 'rec_applicant_document',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
