# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0006_location_employee_employment_type_employmentcontract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0002_workflowattachment_workflowactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('BASIC', 'Basic Pay'), ('HOUSING', 'Housing Allowance'), ('TRANSPORT', 'Transport Allowance'), ('UTILITY', 'Utility Allowance'), ('ALLOWANCE', 'General Allowance'), ('OVERTIME', 'Overtime Pay'), ('BONUS', 'Bonus')], max_length=20)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_pensionable', models.BooleanField(default=False)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comp_salary_component',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_date', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('total_ctc', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='BND', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('components', models.JSONField(default=list, help_text='[{"component_id": "...", "component_name": "...", "amount": 0, "currency": "BND"}]')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='core_hr.employee')),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'comp_employee_package',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='CompensationChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('INCREMENT', 'Increment'), ('BONUS', 'Bonus'), ('ADJUSTMENT', 'Adjustment'), ('PROMOTION', 'Promotion'), ('DEMOTION', 'Demotion'), ('REVISION', 'Revision')], max_length=20)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comp_changes_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comp_changes', to='core_hr.employee')),
                ('new_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compensation.employeepackage')),
                ('previous_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compensation.employeepackage')),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'comp_change',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('bonus_type', models.CharField(choices=[('PERFORMANCE', 'Performance Bonus'), ('DISCRETIONARY', 'Discretionary Bonus'), ('ANNUAL', 'Annual Bonus'), ('FESTIVE', 'Festive Bonus'), ('SPECIAL', 'Special Bonus')], max_length=20)),
                ('budget_pool', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='BND', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_cycles_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonus_cycles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comp_bonus_cycle',
                'ordering': ['-year', 'name'],
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BND', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_bands', to='compensation.salarycomponent')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_bands', to='core_hr.grade')),
            ],
            options={
                'db_table': 'comp_grade_band',
                'ordering': ['grade', 'component'],
                'unique_together': {('grade', 'component')},
            },
        ),
        migrations.CreateModel(
            name='BonusAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommended_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('performance_rating', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_approvals', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='compensation.bonuscycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonus_allocations', to='core_hr.employee')),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comp_bonus_allocation',
                'ordering': ['-created_at'],
                'unique_together': {('cycle', 'employee')},
            },
        ),
    ]
