# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0006_location_employee_employment_type_employmentcontract_and_more'),
        ('learning', '0002_course_workflow_request_skillgap_workflow_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTranscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_hours_completed', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_courses_completed', models.PositiveIntegerField(default=0)),
                ('total_certificates_earned', models.PositiveIntegerField(default=0)),
                ('mandatory_completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_completion_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_transcript', to='core_hr.employee')),
            ],
            options={
                'db_table': 'lms_transcript',
            },
        ),
    ]
