# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0006_location_employee_employment_type_employmentcontract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HSEIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical'), ('FATALITY', 'Fatality')], max_length=20)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('ACTION_REQUIRED', 'Action Required'), ('CLOSED', 'Closed'), ('DISMISSED', 'Dismissed')], default='REPORTED', max_length=30)),
                ('employees_involved', models.JSONField(blank=True, default=list)),
                ('witness_names', models.JSONField(blank=True, default=list)),
                ('immediate_action_taken', models.TextField(blank=True)),
                ('is_work_related', models.BooleanField(default=True)),
                ('is_notifiable', models.BooleanField(default=False)),
                ('notification_authority', models.CharField(blank=True, max_length=255)),
                ('root_cause_identified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hse_incident',
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='HSEIncidentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('default_severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical'), ('FATALITY', 'Fatality')], default='MINOR', max_length=20)),
                ('requires_investigation', models.BooleanField(default=True)),
                ('notification_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hse_incident_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WellbeingProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('program_type', models.CharField(choices=[('MENTAL_HEALTH', 'Mental Health'), ('PHYSICAL_FITNESS', 'Physical Fitness'), ('FINANCIAL_WELLNESS', 'Financial Wellness'), ('SOCIAL', 'Social'), ('ERGONOMICS', 'Ergonomics'), ('NUTRITION', 'Nutrition'), ('OTHER', 'Other')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('target_audience', models.CharField(blank=True, max_length=255)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('current_enrollment', models.PositiveIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wellbeing_programs_created', to=settings.AUTH_USER_MODEL)),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wellbeing_programs_facilitated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hse_wellbeing_program',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalFitnessRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_date', models.DateField()),
                ('fitness_status', models.CharField(choices=[('FIT', 'Fit'), ('FIT_WITH_RESTRICTIONS', 'Fit with Restrictions'), ('TEMPORARILY_UNFIT', 'Temporarily Unfit'), ('PERMANENTLY_UNFIT', 'Permanently Unfit')], max_length=30)),
                ('restrictions', models.TextField(blank=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('assessed_by', models.CharField(blank=True, max_length=255)),
                ('medical_facility', models.CharField(blank=True, max_length=255)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='hse/medical/')),
                ('is_confidential', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_fitness_records', to='core_hr.employee')),
            ],
            options={
                'db_table': 'hse_medical_fitness',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='IncidentInvestigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_members', models.JSONField(blank=True, default=list)),
                ('investigation_start', models.DateField()),
                ('target_close_date', models.DateField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True)),
                ('contributing_factors', models.TextField(blank=True)),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='hse/investigation_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='hse.hseincident')),
                ('lead_investigator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hse_investigations_led', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hse_investigation',
                'ordering': ['-investigation_start'],
            },
        ),
        migrations.AddField(
            model_name='hseincident',
            name='incident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='hse.hseincidenttype'),
        ),
        migrations.AddField(
            model_name='hseincident',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hse_incidents_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_description', models.TextField()),
                ('action_type', models.CharField(choices=[('CORRECTIVE', 'Corrective'), ('PREVENTIVE', 'Preventive'), ('BOTH', 'Both')], default='CORRECTIVE', max_length=20)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('completion_evidence', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hse_actions_assigned', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_corrective_actions', to='hse.hseincident')),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to='hse.incidentinvestigation')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hse_actions_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hse_corrective_action',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='WellbeingEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn'), ('NO_SHOW', 'No Show')], default='ACTIVE', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('attendance_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wellbeing_enrollments', to='core_hr.employee')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='hse.wellbeingprogram')),
            ],
            options={
                'db_table': 'hse_wellbeing_enrollment',
                'unique_together': {('program', 'employee')},
            },
        ),
        migrations.AddIndex(
            model_name='hseincident',
            index=models.Index(fields=['status', 'severity'], name='hse_inciden_status_59b328_idx'),
        ),
    ]
