# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0006_location_employee_employment_type_employmentcontract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0002_workflowattachment_workflowactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('recognition_category', models.CharField(choices=[('PEER', 'Peer Recognition'), ('MANAGER', 'Manager Recognition'), ('COMPANY', 'Company Award'), ('MILESTONE', 'Milestone Award'), ('ANNIVERSARY', 'Service Anniversary')], max_length=20)),
                ('points_value', models.PositiveIntegerField(default=0)),
                ('badge_icon', models.CharField(blank=True, max_length=100)),
                ('requires_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'engagement_recognition_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('survey_type', models.CharField(choices=[('PULSE', 'Pulse Survey'), ('ENGAGEMENT', 'Engagement Survey'), ('ENPS', 'eNPS Survey'), ('EXIT', 'Exit Survey'), ('ONBOARDING', 'Onboarding Survey'), ('360_FEEDBACK', '360 Feedback'), ('CUSTOM', 'Custom Survey')], default='CUSTOM', max_length=20)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'engagement_survey_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionNomination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('justification', models.TextField()),
                ('supporting_evidence', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nominator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominations_made', to='core_hr.employee')),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominations_received', to='core_hr.employee')),
                ('recognition_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engagement.recognitiontype')),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'engagement_recognition_nomination',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionAward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nominated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards_given', to='core_hr.employee')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards_received', to='core_hr.employee')),
                ('recognition_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engagement.recognitiontype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'engagement_recognition_award',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_audience', models.CharField(choices=[('ALL', 'All Employees'), ('ORG_UNIT', 'Org Unit'), ('GRADE', 'Grade'), ('DEPARTMENT', 'Department'), ('CUSTOM', 'Custom List')], default='ALL', max_length=20)),
                ('target_ids', models.JSONField(blank=True, default=list)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('anonymity_threshold', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('launched_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveys_launched', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='engagement.surveytemplate')),
            ],
            options={
                'db_table': 'engagement_survey',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_earned', models.PositiveIntegerField(default=0)),
                ('total_redeemed', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_points', to='core_hr.employee')),
            ],
            options={
                'db_table': 'engagement_employee_points',
            },
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('focus_area', models.CharField(max_length=255)),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('progress_notes', models.TextField(blank=True)),
                ('completion_percentage', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plans_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plans_created', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plans', to='engagement.engagementsurvey')),
            ],
            options={
                'db_table': 'engagement_action_plan',
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_token', models.CharField(max_length=64, unique=True)),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('enps_score', models.SmallIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='core_hr.employee')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='engagement.engagementsurvey')),
            ],
            options={
                'db_table': 'engagement_survey_response',
                'unique_together': {('survey', 'employee')},
            },
        ),
    ]
