# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0006_location_employee_employment_type_employmentcontract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0002_workflowattachment_workflowactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESSRequestType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PROFILE_UPDATE', 'Profile Update'), ('DOCUMENT_REQUEST', 'Document Request'), ('LEAVE', 'Leave'), ('CLAIM', 'Claim'), ('TRAINING', 'Training'), ('IT_ACCESS', 'IT Access'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('requires_approval', models.BooleanField(default=True)),
                ('workflow_code', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ess_request_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfileChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(blank=True, max_length=255)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('evidence_document', models.FileField(blank=True, null=True, upload_to='ess/profile_changes/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_change_requests', to='core_hr.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_changes_reviewed', to=settings.AUTH_USER_MODEL)),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'ess_profile_change_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerDelegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delegation_type', models.CharField(choices=[('LEAVE_APPROVAL', 'Leave Approval'), ('ALL_APPROVALS', 'All Approvals'), ('SPECIFIC_WORKFLOW', 'Specific Workflow')], max_length=30)),
                ('workflow_code', models.CharField(blank=True, max_length=100)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations_created', to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations_received', to='core_hr.employee')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations_given', to='core_hr.employee')),
            ],
            options={
                'db_table': 'ess_manager_delegation',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='ESSRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ess_requests', to='core_hr.employee')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='ess.essrequesttype')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ess_resolved', to=settings.AUTH_USER_MODEL)),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'ess_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
