# Generated by Django 4.2.16 on 2026-05-25 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='succession_plans_approved', to=settings.AUTH_USER_MODEL)),
                ('incumbent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='succession_plans_as_incumbent', to='core_hr.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='succession_plans', to='core_hr.position')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='succession_plans_prepared', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suc_plan',
                'ordering': ['-plan_year'],
                'unique_together': {('position', 'plan_year')},
            },
        ),
        migrations.CreateModel(
            name='TalentPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tier', models.CharField(choices=[('HI_POT', 'High Potential'), ('HI_PERF', 'High Performer'), ('CORE', 'Core Contributor'), ('WATCH', 'Watch List')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'suc_talent_pool',
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nine_box_score', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Low Performance / Low Potential'), (2, 'Low Performance / Moderate Potential'), (3, 'Low Performance / High Potential'), (4, 'Moderate Performance / Low Potential'), (5, 'Moderate Performance / Moderate Potential'), (6, 'Moderate Performance / High Potential'), (7, 'High Performance / Low Potential'), (8, 'High Performance / Moderate Potential'), (9, 'High Performance / High Potential')], null=True)),
                ('flight_risk', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('career_aspirations', models.TextField(blank=True)),
                ('key_strengths', models.TextField(blank=True)),
                ('development_areas', models.TextField(blank=True)),
                ('mobility_preference', models.CharField(choices=[('LOCAL', 'Local Only'), ('DOMESTIC', 'Domestic'), ('INTERNATIONAL', 'International'), ('ANY', 'Any Location')], default='LOCAL', max_length=20)),
                ('last_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_assessments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent_profile', to='core_hr.employee')),
                ('talent_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='succession.talentpool')),
            ],
            options={
                'db_table': 'suc_talent_profile',
            },
        ),
        migrations.CreateModel(
            name='SuccessorNomination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('readiness_level', models.CharField(choices=[('IMMEDIATE', 'Ready Now'), ('1_2_YEARS', 'Ready in 1-2 Years'), ('3_5_YEARS', 'Ready in 3-5 Years'), ('LONG_TERM', 'Long Term (5+ Years)')], max_length=20)),
                ('priority_rank', models.PositiveIntegerField(default=1)),
                ('strengths', models.TextField(blank=True)),
                ('development_needs', models.TextField(blank=True)),
                ('is_willing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='successor_nominations', to='core_hr.employee')),
                ('nominated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='successor_nominations_made', to=settings.AUTH_USER_MODEL)),
                ('succession_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='succession.successionplan')),
            ],
            options={
                'db_table': 'suc_nominee',
                'ordering': ['priority_rank'],
                'unique_together': {('succession_plan', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='DevelopmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('target_completion_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('progress_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='development_plans_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_plans', to='core_hr.employee')),
                ('succession_nominee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='development_plans', to='succession.successornomination')),
            ],
            options={
                'db_table': 'suc_dev_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('TRAINING', 'Training'), ('MENTORING', 'Mentoring'), ('STRETCH_ASSIGNMENT', 'Stretch Assignment'), ('COACHING', 'Coaching'), ('CERTIFICATION', 'Certification'), ('JOB_ROTATION', 'Job Rotation')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('development_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='succession.developmentplan')),
            ],
            options={
                'db_table': 'suc_dev_activity',
                'ordering': ['target_date'],
            },
        ),
    ]
