# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0006_location_employee_employment_type_employmentcontract_and_more'),
        ('succession', '0002_successionplan_workflow_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rationale', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('time_to_fill_days', models.PositiveIntegerField(default=90)),
                ('has_identified_successor', models.BooleanField(default=False)),
                ('minimum_successors_required', models.PositiveIntegerField(default=2)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='critical_role', to='core_hr.position')),
            ],
            options={
                'db_table': 'suc_critical_role',
                'ordering': ['position__title'],
            },
        ),
    ]
