# Generated by Django 4.2.16 on 2026-05-25 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('max_level', models.PositiveSmallIntegerField(default=5)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'perf_competency',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'perf_competency_model',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('KPI', 'KPI / Quantitative'), ('PROJECT', 'Project'), ('DEVELOPMENT', 'Development'), ('BEHAVIORAL', 'Behavioral')], default='KPI', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('target_value', models.CharField(blank=True, max_length=255)),
                ('unit_of_measure', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'perf_goal',
                'ordering': ['-weight', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cycle_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('GOAL_SETTING', 'Goal Setting'), ('MID_YEAR', 'Mid-Year Review'), ('YEAR_END', 'Year-End Review'), ('CALIBRATION', 'Calibration'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('goal_setting_start', models.DateField()),
                ('goal_setting_end', models.DateField()),
                ('mid_year_start', models.DateField(blank=True, null=True)),
                ('mid_year_end', models.DateField(blank=True, null=True)),
                ('year_end_start', models.DateField()),
                ('year_end_end', models.DateField()),
                ('calibration_start', models.DateField(blank=True, null=True)),
                ('calibration_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'perf_cycle',
                'ordering': ['-cycle_year'],
            },
        ),
        migrations.CreateModel(
            name='ReviewForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_type', models.CharField(choices=[('SELF', 'Self Assessment'), ('MANAGER', 'Manager Review'), ('PEER', 'Peer Review'), ('360', '360 Degree Review')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('ACKNOWLEDGED', 'Acknowledged')], default='DRAFT', max_length=20)),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('strengths_comments', models.TextField(blank=True)),
                ('improvement_comments', models.TextField(blank=True)),
                ('overall_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_forms', to='performance.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_forms', to='core_hr.employee')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_forms_as_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_review_form',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_ratings', to='performance.competency')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_ratings', to='performance.goal')),
                ('review_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='performance.reviewform')),
            ],
            options={
                'db_table': 'perf_review_rating',
            },
        ),
        migrations.CreateModel(
            name='ImprovementPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('objectives', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='ACTIVE', max_length=20)),
                ('outcome_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_plans', to='performance.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_plans', to='core_hr.employee')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='improvement_plans_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_improvement_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_date', models.DateField()),
                ('current_value', models.CharField(blank=True, max_length=255)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='performance.goal')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goal_progress_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perf_goal_progress',
                'ordering': ['-update_date'],
            },
        ),
        migrations.CreateModel(
            name='GoalPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('MANAGER_APPROVED', 'Manager Approved'), ('HR_APPROVED', 'HR Approved'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('overall_weight_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_plans_approved', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goal_plans', to='performance.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_plans', to='core_hr.employee')),
            ],
            options={
                'db_table': 'perf_goal_plan',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'cycle')},
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='performance.goalplan'),
        ),
        migrations.AddField(
            model_name='competency',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='performance.competencymodel'),
        ),
        migrations.CreateModel(
            name='CalibrationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_sessions', to='performance.performancecycle')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_sessions_facilitated', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_sessions', to='core_hr.orgunit')),
            ],
            options={
                'db_table': 'perf_calibration_session',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='FinalOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('outcome_label', models.CharField(choices=[('EXCEEDS', 'Exceeds Expectations'), ('MEETS', 'Meets Expectations'), ('PARTIALLY', 'Partially Meets'), ('BELOW', 'Below Expectations')], max_length=20)),
                ('eligible_for_increment', models.BooleanField(default=False)),
                ('eligible_for_bonus', models.BooleanField(default=False)),
                ('increment_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_outcomes_approved', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_outcomes', to='performance.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_outcomes', to='core_hr.employee')),
            ],
            options={
                'db_table': 'perf_final_outcome',
                'ordering': ['-created_at'],
                'unique_together': {('cycle', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='CalibratedRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pre_calibration_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('calibrated_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('calibration_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibrated_ratings', to='core_hr.employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrated_ratings', to='performance.calibrationsession')),
            ],
            options={
                'db_table': 'perf_calibrated_rating',
                'unique_together': {('session', 'employee')},
            },
        ),
    ]
