# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0006_location_employee_employment_type_employmentcontract_and_more'),
        ('performance', '0002_finaloutcome_workflow_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_date', models.DateField()),
                ('goals_discussed', models.JSONField(default=list, help_text='List of goal IDs discussed')),
                ('achievements', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('overall_rating', models.CharField(blank=True, choices=[('ON_TRACK', 'On Track'), ('AT_RISK', 'At Risk'), ('OFF_TRACK', 'Off Track')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins', to='performance.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='core_hr.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_ins_as_manager', to='core_hr.employee')),
            ],
            options={
                'db_table': 'perf_check_in',
                'ordering': ['-check_in_date'],
            },
        ),
        migrations.CreateModel(
            name='CyclePopulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_eligible', models.BooleanField(default=True)),
                ('inclusion_reason', models.CharField(blank=True, max_length=255)),
                ('exclusion_reason', models.CharField(blank=True, max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population', to='performance.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_cycle_memberships', to='core_hr.employee')),
            ],
            options={
                'db_table': 'perf_cycle_population',
                'unique_together': {('cycle', 'employee')},
            },
        ),
    ]
