# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0006_location_employee_employment_type_employmentcontract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('retention_years', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'doc_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RetentionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retention_years', models.PositiveIntegerField()),
                ('disposal_action', models.CharField(choices=[('PERMANENT_DELETE', 'Permanent Delete'), ('ARCHIVE', 'Archive'), ('REVIEW_BEFORE_DELETE', 'Review Before Delete')], max_length=30)),
                ('legal_hold_applicable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_rules', to='documents.doccategory')),
            ],
            options={
                'db_table': 'doc_retention_rule',
            },
        ),
        migrations.CreateModel(
            name='DocTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='documents/templates/')),
                ('variables', models.JSONField(blank=True, default=list)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='documents.doccategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doc_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doc_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('PUBLISHED', 'Published'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('requires_acknowledgement', models.BooleanField(default=False)),
                ('acknowledgement_deadline', models.DateField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/policies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='documents.doccategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doc_policies_created', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_policies_published', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doc_policy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_acknowledged', models.CharField(max_length=20)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('digital_signature', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_acknowledgements', to='core_hr.employee')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='documents.docpolicy')),
            ],
            options={
                'db_table': 'doc_acknowledgement',
            },
        ),
        migrations.CreateModel(
            name='DocRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/records/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_confidential', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='documents.doccategory')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core_hr.employee')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_records', to='documents.doctemplate')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doc_records_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doc_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='doc_record_employe_b2c9c0_idx'), models.Index(fields=['category'], name='doc_record_categor_077465_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='docpolicy',
            index=models.Index(fields=['status', 'effective_date'], name='doc_policy_status_74fc70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='docacknowledgement',
            unique_together={('policy', 'employee', 'version_acknowledged')},
        ),
    ]
