# Generated by Django 4.2.16 on 2026-05-25 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
        ('core_hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='source_onboarding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_employees', to='onboarding.onboardingcase'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='org_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='core_hr.orgunit'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['status', 'org_unit'], name='core_positi_status_da8895_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('valid_to', None)), fields=('employee', 'is_primary'), name='uq_primary_assignment_per_employee'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employment_status'], name='core_employ_employm_f29ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['manager'], name='core_employ_manager_e7a4bc_idx'),
        ),
    ]
