# Generated by Django 4.2.16 on 2026-05-26 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_hr', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_units_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='type',
            field=models.CharField(choices=[('ORGANIZATION', 'Organization'), ('COMPANY', 'Company'), ('DIVISION', 'Division'), ('DEPARTMENT', 'Department'), ('UNIT', 'Unit'), ('BRANCH', 'Branch')], default='DEPARTMENT', max_length=20),
        ),
    ]
