# Generated by Django 4.2.16 on 2026-05-26 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
        ('core_hr', '0003_add_org_type_organization_and_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='workflow_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest'),
        ),
        migrations.AddField(
            model_name='grade',
            name='workflow_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest'),
        ),
        migrations.AddField(
            model_name='job',
            name='workflow_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='workflow_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest'),
        ),
    ]
