# Generated by Django 4.2.16 on 2026-05-25 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('policy_type', models.CharField(choices=[('FIXED', 'Fixed Hours'), ('FLEXIBLE', 'Flexible Hours'), ('SHIFT', 'Shift Based')], default='FIXED', max_length=20)),
                ('standard_hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('grace_minutes', models.PositiveIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wf_attendance_policy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('days_per_year', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('carry_forward', models.BooleanField(default=False)),
                ('max_carry_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wf_leave_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('PROMOTION', 'Promotion'), ('DEMOTION', 'Demotion'), ('LATERAL', 'Lateral Move'), ('SECONDMENT', 'Secondment')], max_length=20)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='core_hr.employee')),
                ('from_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from_grade', to='core_hr.grade')),
                ('from_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='core_hr.position')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_initiated', to=settings.AUTH_USER_MODEL)),
                ('to_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to_grade', to='core_hr.grade')),
                ('to_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='core_hr.position')),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'wf_transfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Separation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('separation_type', models.CharField(choices=[('RESIGNATION', 'Resignation'), ('TERMINATION', 'Termination'), ('RETIREMENT', 'Retirement'), ('END_OF_CONTRACT', 'End of Contract'), ('REDUNDANCY', 'Redundancy'), ('DEATH', 'Death')], max_length=30)),
                ('notice_date', models.DateField()),
                ('last_working_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=20)),
                ('clearance_completed', models.BooleanField(default=False)),
                ('exit_interview_done', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separations_approved', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='separation', to='core_hr.employee')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='separations_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wf_separation',
                'ordering': ['-notice_date'],
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=100)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rosters_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rosters', to='core_hr.employee')),
            ],
            options={
                'db_table': 'wf_roster',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours_requested', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hours_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_requests', to='core_hr.employee')),
            ],
            options={
                'db_table': 'wf_overtime_request',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_requested', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='core_hr.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='workforce.leavetype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wf_leave_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkforcePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('headcount_current', models.PositiveIntegerField(default=0)),
                ('headcount_target', models.PositiveIntegerField(default=0)),
                ('attrition_forecast', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_plans_approved', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workforce_plans', to='core_hr.orgunit')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workforce_plans_prepared', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wf_plan',
                'ordering': ['-plan_year'],
                'unique_together': {('plan_year', 'org_unit')},
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('entitled_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pending_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carried_forward', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='core_hr.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='workforce.leavetype')),
            ],
            options={
                'db_table': 'wf_leave_balance',
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_present', models.BooleanField(default=True)),
                ('is_late', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('BIOMETRIC', 'Biometric'), ('MANUAL', 'Manual Entry'), ('MOBILE', 'Mobile App'), ('SYSTEM', 'System')], default='BIOMETRIC', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_logs', to='core_hr.employee')),
            ],
            options={
                'db_table': 'wf_attendance_log',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
