# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_hr', '0006_location_employee_employment_type_employmentcontract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workforce', '0002_leaverequest_workflow_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wf_holiday_calendar',
                'ordering': ['-year', 'country'],
                'unique_together': {('year', 'country')},
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('days_of_week', models.JSONField(default=list, help_text='List of day numbers: 0=Monday, 1=Tuesday, ..., 6=Sunday')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_templates_created', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_templates', to='workforce.attendancepolicy')),
            ],
            options={
                'db_table': 'wf_shift_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employment_type', models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern')], max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('', 'All'), ('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('days_entitled', models.DecimalField(decimal_places=2, max_digits=5)),
                ('accrual_method', models.CharField(choices=[('NONE', 'None - Full entitlement upfront'), ('MONTHLY', 'Monthly Accrual'), ('YEARLY', 'Yearly Accrual'), ('ANNUAL', 'Annual Award')], default='ANNUAL', max_length=20)),
                ('max_carry_forward', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('requires_medical_cert', models.BooleanField(default=False)),
                ('min_service_months', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_policies', to='core_hr.grade')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='workforce.leavetype')),
            ],
            options={
                'db_table': 'wf_leave_policy',
                'ordering': ['leave_type', 'grade'],
            },
        ),
        migrations.CreateModel(
            name='LeaveDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='leave/documents/')),
                ('document_type', models.CharField(choices=[('MEDICAL_CERTIFICATE', 'Medical Certificate'), ('SUPPORTING_DOCUMENT', 'Supporting Document'), ('OTHER', 'Other')], default='SUPPORTING_DOCUMENT', max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workforce.leaverequest')),
            ],
            options={
                'db_table': 'wf_leave_document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_type', models.CharField(choices=[('LATE_ARRIVAL', 'Late Arrival'), ('EARLY_DEPARTURE', 'Early Departure'), ('ABSENT', 'Absent'), ('INCOMPLETE', 'Incomplete Record'), ('BREAK_EXCEEDED', 'Break Time Exceeded')], max_length=30)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='workforce.attendancelog')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_exceptions_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wf_attendance_exception',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='HolidayCalendarEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('holiday_type', models.CharField(choices=[('PUBLIC', 'Public Holiday'), ('RESTRICTED', 'Restricted Holiday'), ('COMPANY', 'Company Holiday')], default='PUBLIC', max_length=20)),
                ('is_paid', models.BooleanField(default=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='workforce.holidaycalendar')),
            ],
            options={
                'db_table': 'wf_holiday_entry',
                'ordering': ['date'],
                'unique_together': {('calendar', 'date')},
            },
        ),
    ]
