# Generated by Django 4.2.16 on 2026-05-25 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_code', models.CharField(max_length=50)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.UUIDField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('RETURNED', 'Returned for Amendment'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('ACTIVE', 'Active')], default='DRAFT', max_length=30)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maker_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_code', models.CharField(max_length=100, unique=True)),
                ('module_code', models.CharField(max_length=50)),
                ('applies_to', models.CharField(help_text='e.g. recruitment.job_posting', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('steps', models.JSONField(default=list, help_text='[{"step": 1, "role": "HR_CHECKER", "sla_hours": 24}, ...]')),
                ('segregation_of_duties', models.BooleanField(default=True)),
                ('maker_cannot_approve', models.BooleanField(default=True)),
                ('audit_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workflow_rule',
                'ordering': ['module_code', 'workflow_code'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField()),
                ('approver_role', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('action', models.CharField(blank=True, max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('sla_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps_to_approve', to=settings.AUTH_USER_MODEL)),
                ('workflow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'workflow_step',
                'ordering': ['step_number'],
                'unique_together': {('workflow_request', 'step_number')},
            },
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='workflow_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='workflow.workflowrule'),
        ),
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('step_number', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('before_snapshot', models.JSONField(blank=True, null=True)),
                ('after_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workflow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'workflow_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('visibility', models.CharField(choices=[('ALL', 'All Parties'), ('INTERNAL', 'Internal Only')], default='ALL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowstep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workflow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'workflow_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowrequest',
            index=models.Index(fields=['module_code', 'object_type', 'object_id'], name='workflow_re_module__09750c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrequest',
            index=models.Index(fields=['status', '-created_at'], name='workflow_re_status_5b865f_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrequest',
            index=models.Index(fields=['maker_user', '-created_at'], name='workflow_re_maker_u_ae99c6_idx'),
        ),
    ]
