# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='workflow/attachments/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_attachments', to=settings.AUTH_USER_MODEL)),
                ('workflow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'workflow_attachment',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowActor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('INITIATOR', 'Initiator'), ('CHECKER', 'Checker'), ('APPROVER', 'Approver'), ('OBSERVER', 'Observer')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_actor_roles', to=settings.AUTH_USER_MODEL)),
                ('workflow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'workflow_actor',
                'ordering': ['assigned_at'],
                'unique_together': {('workflow_request', 'user', 'role')},
            },
        ),
    ]
