# Generated by Django 4.2.16 on 2026-05-25 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitment', '0001_initial'),
        ('core_hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('PENDING_HR', 'Pending HR Review'), ('COMPLETED', 'Completed'), ('WAIVED', 'Waived'), ('CANCELLED', 'Cancelled')], default='STARTED', max_length=20)),
                ('target_start_date', models.DateField()),
                ('hr_verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_hr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_cases_managed', to=settings.AUTH_USER_MODEL)),
                ('candidate_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_cases', to='core_hr.person')),
                ('hr_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_cases_verified', to=settings.AUTH_USER_MODEL)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_case', to='recruitment.offer')),
            ],
            options={
                'db_table': 'onb_case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tasks', models.JSONField(default=list, help_text='[{"task_code": "PERSONAL_INFO", "title": "...", "required": true, "order": 1}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'onb_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_code', models.CharField(choices=[('PERSONAL_INFO', 'Personal Information Verification'), ('RESUME', 'Resume Verification'), ('ACADEMIC_CERTS', 'Academic Certificates'), ('PROFESSIONAL_CERTS', 'Professional Certifications'), ('BANK_DETAILS', 'Bank Account Details'), ('EMERGENCY_CONTACT', 'Emergency Contact'), ('CONTRACT_SIGNING', 'Employment Contract Signing'), ('ACCESS_REQUEST', 'Access Provisioning Request'), ('PAYROLL_SETUP', 'Payroll Setup'), ('CUSTOM', 'Custom Task')], default='CUSTOM', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('WAIVED', 'Waived'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_tasks_completed', to=settings.AUTH_USER_MODEL)),
                ('onboarding_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='onboarding.onboardingcase')),
            ],
            options={
                'db_table': 'onb_task',
                'ordering': ['order', 'task_code'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('RESUME', 'Resume'), ('ID_COPY', 'ID Copy'), ('ACADEMIC', 'Academic Certificate'), ('PROFESSIONAL', 'Professional Certification'), ('BANK', 'Bank Details'), ('CONTRACT', 'Employment Contract'), ('OTHER', 'Other')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='onboarding/documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='onboarding.onboardingcase')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='onboarding.onboardingtask')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_onboarding_docs', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_onboarding_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onb_document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='onboardingcase',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='onboarding.onboardingtemplate'),
        ),
    ]
