# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0006_location_employee_employment_type_employmentcontract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0002_workflowattachment_workflowactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('expense_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BND', max_length=10)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'claims_claim_line',
                'ordering': ['expense_date'],
            },
        ),
        migrations.CreateModel(
            name='ClaimType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('MEDICAL', 'Medical'), ('TRANSPORT', 'Transport'), ('MEALS', 'Meals'), ('ACCOMMODATION', 'Accommodation'), ('TRAINING', 'Training'), ('PROFESSIONAL_DEV', 'Professional Development'), ('MISCELLANEOUS', 'Miscellaneous')], max_length=30)),
                ('max_amount_per_claim', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_amount_per_year', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('requires_receipt', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'claims_claim_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('country_of_travel', models.CharField(blank=True, max_length=100)),
                ('purpose', models.TextField()),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('travel_type', models.CharField(choices=[('DOMESTIC', 'Domestic'), ('INTERNATIONAL', 'International')], default='DOMESTIC', max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='BND', max_length=10)),
                ('advance_requested', models.BooleanField(default=False)),
                ('advance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('advance_settled', models.BooleanField(default=False)),
                ('itinerary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_requests', to='core_hr.employee')),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'claims_travel_request',
                'ordering': ['-departure_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpensePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('mileage_rate_per_km', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('per_diem_domestic', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_diem_international', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('meal_allowance_breakfast', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('meal_allowance_lunch', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('meal_allowance_dinner', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_policies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claims_expense_policy',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('claim_title', models.CharField(max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='BND', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_approved', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_requests', to='core_hr.employee')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_paid', to=settings.AUTH_USER_MODEL)),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'claims_claim_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='claims/receipts/')),
                ('receipt_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='claims.claimrequest')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='claims.claimline')),
            ],
            options={
                'db_table': 'claims_claim_receipt',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='claimline',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='claims.claimrequest'),
        ),
        migrations.AddField(
            model_name='claimline',
            name='claim_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_lines', to='claims.claimtype'),
        ),
        migrations.AddIndex(
            model_name='claimrequest',
            index=models.Index(fields=['employee', 'status'], name='claims_clai_employe_e85fdf_idx'),
        ),
    ]
