# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0003_learningtranscript'),
        ('core_hr', '0006_location_employee_employment_type_employmentcontract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_self_assessed', models.BooleanField(default=True)),
                ('is_endorsed', models.BooleanField(default=False)),
                ('endorsed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_description', models.TextField(blank=True)),
                ('assessed_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core_hr.employee')),
                ('endorsed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_endorsements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skills_employee_skill',
            },
        ),
        migrations.CreateModel(
            name='ProficiencyScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('level', models.PositiveIntegerField(unique=True)),
                ('behavioural_indicators', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'skills_proficiency_scale',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_date', models.DateField(auto_now_add=True)),
                ('overall_match_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gaps_summary', models.JSONField(blank=True, default=list)),
                ('recommended_training', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_analyses', to='core_hr.employee')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_gap_analyses', to='core_hr.job')),
            ],
            options={
                'db_table': 'skills_gap_analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('evidence_type', models.CharField(choices=[('CERTIFICATE', 'Certificate'), ('PROJECT', 'Project'), ('TRAINING_COMPLETION', 'Training Completion'), ('ASSESSMENT', 'Assessment'), ('ENDORSEMENT', 'Endorsement'), ('PUBLICATION', 'Publication'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='skills/evidence/')),
                ('url', models.CharField(blank=True, max_length=500)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='skills.employeeskill')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_evidence_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skills_evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='skills.skillcategory')),
            ],
            options={
                'db_table': 'skills_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='skills.skillcategory')),
            ],
            options={
                'db_table': 'skills_skill',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobSkillRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='core_hr.job')),
                ('required_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_requirements', to='skills.proficiencyscale')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requirements', to='skills.skill')),
            ],
            options={
                'db_table': 'skills_job_requirement',
            },
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='proficiency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_skills', to='skills.proficiencyscale'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assessments', to='skills.skill'),
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gap_size', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('target_closure_date', models.DateField(blank=True, null=True)),
                ('current_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_gaps', to='skills.proficiencyscale')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_skill_gaps', to='core_hr.employee')),
                ('recommended_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_gaps_recommended', to='learning.course')),
                ('required_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='required_for_gaps', to='skills.proficiencyscale')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='skills.skill')),
            ],
            options={
                'db_table': 'skills_gap',
                'unique_together': {('employee', 'skill')},
            },
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category', 'is_active'], name='skills_skil_categor_1b1829_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobskillrequirement',
            unique_together={('job', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeskill',
            unique_together={('employee', 'skill')},
        ),
    ]
