# Generated by Django 4.2.16 on 2026-05-26 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_hr', '0003_add_org_type_organization_and_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDescriptor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descriptor', models.JSONField()),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_descriptor', to='core_hr.employee')),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_faces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_face_descriptor',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('FACE', 'Face Recognition'), ('MANUAL', 'Manual')], default='FACE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core_hr.employee')),
            ],
            options={
                'db_table': 'attendance_record',
                'ordering': ['-date', '-check_in'],
                'indexes': [models.Index(fields=['date'], name='attendance__date_21321a_idx'), models.Index(fields=['employee', 'date'], name='attendance__employe_9ec8ab_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
