# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0006_location_employee_employment_type_employmentcontract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0002_workflowattachment_workflowactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('pay_group', models.CharField(choices=[('MONTHLY', 'Monthly'), ('BIWEEKLY', 'Bi-Weekly'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly')], default='MONTHLY', max_length=20)),
                ('frequency', models.CharField(blank=True, help_text='Description of pay frequency', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_calendars_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_calendar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('BASIC', 'Basic Pay'), ('ALLOWANCE', 'Allowance'), ('DEDUCTION', 'Deduction'), ('CONTRIBUTION', 'Employer Contribution'), ('TAX', 'Tax')], max_length=20)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_pensionable', models.BooleanField(default=False)),
                ('formula', models.JSONField(default=dict, help_text='{"type": "fixed", "value": 0}')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payroll_element',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('LOCKED', 'Locked'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('total_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_deductions', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_net', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_approved', to=settings.AUTH_USER_MODEL)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='payroll.payrollcalendar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_created', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_processed', to=settings.AUTH_USER_MODEL)),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'payroll_run',
                'ordering': ['-period_start'],
                'unique_together': {('calendar', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_deduction', models.BooleanField(default=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslip_lines', to='payroll.payrollelement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslip_lines', to='core_hr.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrollrun')),
            ],
            options={
                'db_table': 'payroll_payslip_line',
                'ordering': ['element__display_order'],
            },
        ),
        migrations.CreateModel(
            name='PayrollGLPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gl_account', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('posting_date', models.DateField()),
                ('is_posted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_gl_postings', to='core_hr.costcenter')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_postings', to='payroll.payrollrun')),
            ],
            options={
                'db_table': 'payroll_gl_posting',
                'ordering': ['posting_date', 'gl_account'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_adjustments_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='payroll.payrollelement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments', to='core_hr.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payrollrun')),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'payroll_adjustment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePayrollProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=100)),
                ('bank_code', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_profiles', to='payroll.payrollcalendar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_profiles_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_profile', to='core_hr.employee')),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'payroll_employee_profile',
                'ordering': ['employee__employee_number'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basic_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pension_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payslip_date', models.DateField()),
                ('is_locked', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='core_hr.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
            ],
            options={
                'db_table': 'payroll_payslip',
                'ordering': ['-payslip_date'],
                'unique_together': {('payroll_run', 'employee')},
            },
        ),
    ]
