# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0006_location_employee_employment_type_employmentcontract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0002_workflowattachment_workflowactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitClaimReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_reference', models.CharField(blank=True, max_length=100)),
                ('claim_date', models.DateField()),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REIMBURSED', 'Reimbursed')], default='SUBMITTED', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='benefits/claims/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'benefits_claim_reference',
                'ordering': ['-claim_date'],
            },
        ),
        migrations.CreateModel(
            name='BenefitPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('MEDICAL', 'Medical'), ('DENTAL', 'Dental'), ('VISION', 'Vision'), ('LIFE', 'Life Insurance'), ('PENSION', 'Pension / Retirement'), ('EDUCATION', 'Education'), ('RECREATION', 'Recreation'), ('OTHER', 'Other')], max_length=20)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('coverage_details', models.JSONField(default=dict)),
                ('employee_contribution_rate', models.DecimalField(decimal_places=4, default=0, help_text='Employee contribution as a fraction (0-1)', max_digits=5)),
                ('employer_contribution_rate', models.DecimalField(decimal_places=4, default=0, help_text='Employer contribution as a fraction (0-1)', max_digits=5)),
                ('max_dependents', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'benefits_plan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employment_type', models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern')], max_length=20)),
                ('min_service_months', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefit_eligibility_rules', to='core_hr.grade')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='benefits.benefitplan')),
            ],
            options={
                'db_table': 'benefits_eligibility_rule',
                'ordering': ['plan', 'grade'],
            },
        ),
        migrations.CreateModel(
            name='BenefitEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ENDED', 'Ended')], default='ACTIVE', max_length=20)),
                ('employee_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefit_enrollments_approved', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benefit_enrollments', to='core_hr.employee')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='benefits.benefitplan')),
                ('workflow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowrequest')),
            ],
            options={
                'db_table': 'benefits_enrollment',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='BenefitDependent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='benefits.benefitenrollment')),
            ],
            options={
                'db_table': 'benefits_dependent',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BenefitCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('employee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employer_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='benefits.benefitenrollment')),
            ],
            options={
                'db_table': 'benefits_cost',
                'ordering': ['-period_start'],
            },
        ),
    ]
