# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('benefits', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitcost',
            name='payroll_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefit_costs', to='payroll.payrollrun'),
        ),
        migrations.AddField(
            model_name='benefitclaimreference',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefit_claims_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='benefitclaimreference',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='benefits.benefitenrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='benefitenrollment',
            unique_together={('employee', 'plan')},
        ),
    ]
