# Generated by Django 4.2.16 on 2026-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_hr', '0006_location_employee_employment_type_employmentcontract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('PENDING_INFO', 'Pending Info'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('satisfaction_score', models.PositiveIntegerField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sdesk_hr_ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='service_desk/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='service_desk.hrticket')),
            ],
            options={
                'db_table': 'sdesk_ticket_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sla_hours', models.PositiveIntegerField(default=24)),
                ('is_confidential', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='service_desk.ticketcategory')),
            ],
            options={
                'db_table': 'sdesk_ticket_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField()),
                ('feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_surveys', to='service_desk.hrticket')),
            ],
            options={
                'db_table': 'sdesk_satisfaction_survey',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='service_desk.knowledgecategory')),
            ],
            options={
                'db_table': 'sdesk_knowledge_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('helpful_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('views_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='service_desk.knowledgecategory')),
            ],
            options={
                'db_table': 'sdesk_knowledge_article',
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddField(
            model_name='hrticket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='service_desk.ticketcategory'),
        ),
        migrations.AddField(
            model_name='hrticket',
            name='on_behalf_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_on_behalf', to='core_hr.employee'),
        ),
        migrations.AddField(
            model_name='hrticket',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_raised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='hrticket',
            index=models.Index(fields=['status', '-created_at'], name='sdesk_hr_ti_status_44bae2_idx'),
        ),
        migrations.AddIndex(
            model_name='hrticket',
            index=models.Index(fields=['assigned_to', 'status'], name='sdesk_hr_ti_assigne_4c46a8_idx'),
        ),
    ]
